move_group:
  ros__parameters:
    trajectory_execution.allowed_execution_duration_scaling: 10.0
    trajectory_execution.allowed_goal_duration_margin: 10.0
    trajectory_execution.allowed_start_tolerance: 0.02
